---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "phpmdruleset.xml"
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.py"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- tests/**/*
- vendor/**/*
- public/css/app.css
- public/js/app.js
